[build]
  command = "chmod +x node_modules/.bin/vite && npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"  # or your Node version

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
